MinhHoa01/MinhHoa01/Models/ErrorViewModel.cs
using System;

namespace MinhHoa01.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MinhHoa01/MinhHoa01/Models/MayTinhModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinhHoa01.Models
{
    public class MayTinhModel
    {
        public double So1 { get; set; }
        public double So2 { get; set; }
        public string PhepTinh { get; set; }
    }
}

MinhHoa01/MinhHoa01/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinhHoa01.Models
{
    public class PersonViewModel
    {
        public string FullName { get; set; }
        public DateTime BirthDay { get; set; }
        public string Picture { get; set; }
    }
}

MinhHoa01/MinhHoa01/Controllers/GioiThieuController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinhHoa01
{
    public class GioiThieuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BanThan()
        {
            return View();
        }
        public IActionResult ChaMe()
        {
            return View();
        }
        public IActionResult AnhChiEm()
        {
            return View();
        }
    }
}

MinhHoa01/MinhHoa01/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MinhHoa01.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MinhHoa01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MinhHoa01/MinhHoa01/Controllers/MayTinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MinhHoa01.Models;

namespace MinhHoa01.Controllers
{
    public class MayTinhController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //cách 3: tiếp nhận giá trị tham số thông qua Model
        public IActionResult XuLy(MayTinhModel mt)
        {
            //b1.lấy giá trị các tham số (So1, So2, PhepTinh)
            //b2.tinh toan ket qua
            double ketqua = 0;
            switch (mt.PhepTinh)
            {
                case "+": ketqua = mt.So1 + mt.So2; break;
                case "-": ketqua = mt.So1 - mt.So2; break;
                case "*": ketqua = mt.So1 * mt.So2; break;
                case "/": ketqua = mt.So1 / mt.So2; break;
            }
            //b3.Tra ket qua ve nguoi dung
            ViewBag.KQ = ketqua; //truyền dữ liệu cho view thông qua ViewBag
            return View("Index", mt);
        }
    }
}

MinhHoa01/MinhHoa01/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using MinhHoa01.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace MinhHoa01.Controllers
{
    public class RegisterController:Controller
    {
        private IHostingEnvironment hosting;
        public RegisterController(IHostingEnvironment _hosting)
        {
            hosting = _hosting;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult XuLy(PersonViewModel m, IFormFile FHinh)
        {
            if (FHinh != null)
            {
                //xử lý upload
                // string filename = FHinh.FileName;
                string filename = Guid.NewGuid().ToString() + Path.GetExtension(FHinh.FileName);
                string path = Path.Combine(hosting.WebRootPath, "images");
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                {
                    //sao chép lên server
                    FHinh.CopyTo(filestream);
                }
                m.Picture = filename;
            }
            return View(m);
        }
    }
}

MinhHoa01/MinhHoa01/Views/GioiThieu/AnhChiEm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h3> Tên:D</h3>
    <h3> Tên:E</h3>
    <h3> Tên:F</h3>
</div>

MinhHoa01/MinhHoa01/Views/GioiThieu/BanThan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h3> Tên:A</h3>
</div>

MinhHoa01/MinhHoa01/Views/GioiThieu/ChaMe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h3> Tên:B</h3>
    <h3> Tên:C</h3>
</div>

MinhHoa01/MinhHoa01/Views/GioiThieu/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<div>
    <h2>Chào Mừng </h2>
    <ul>
        <li><a asp-controller="GioiThieu" asp-action="BanThan">Thông Tin Bản Thân</a></li>
        <li><a asp-controller="GioiThieu" asp-action="ChaMe">Thông Tin Cha Mẹ</a> </li>
        <li><a asp-controller="GioiThieu" asp-action="AnhChiEm">Thông Tin Anh Chi Em</a> </li>
    </ul>
</div>

MinhHoa01/MinhHoa01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MinhHoa01/MinhHoa01/Views/Register/Index.cshtml
@model PersonViewModel
<h2>THÔNG TIN ĐĂNG KÝ</h2>
<hr />
<form asp-action="XuLy" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Họ tên</label>
        <input asp-for="FullName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Ngày sinh</label>
        <input asp-for="BirthDay" type="date" class="form-control" />
    </div>
    <div class="form-group">
        <label>Hình đại diện</label>
        <input name="FHinh" type="file" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Đăng ký</button>
</form>

MinhHoa01/MinhHoa01/Views/Register/XuLy.cshtml
@model PersonViewModel
<h3>Thông tin đăng ký</h3>
<hr />
<ul>
    <li>Họ tên: <b> @Model.FullName </b></li>
    <li>Ngày sinh:<b> @Model.BirthDay.ToString("dd/MM/yyyy") </b> </li>
    <li>
        Hình đại diện: <br>
        <img src="/images/@Model.Picture" width="200px" />
    </li>
</ul>

MinhHoa01/MinhHoa01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinhHoa01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MinhHoa01</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MinhHoa01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>