WebBanHang/WebBanHang/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController:Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        //Hiển thị danh sách chủng loại
        public IActionResult Index()
        {
            var listCategory = _db.Categories.ToList();
            return View(listCategory);
        }
        //Hiển thị form thêm mới chủng loại
        public IActionResult Add()
        {
            return View();
        }
        // Xử lý thêm chủng loại mới
        [HttpPost]
        public IActionResult Add(Category category)
        {
            if (ModelState.IsValid) //kiem tra hop le
            {
                //thêm category vào table Categories
                _db.Categories.Add(category);
                _db.SaveChanges();
            TempData["success"] = "Thêm Thành Công";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Hiển thị form cập nhật chủng loại
        public IActionResult Update(int id)
        {
            var category = _db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        // Xử lý cập nhật chủng loại
        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (ModelState.IsValid) //kiem tra hop le
            {
                //cập nhật category vào table Categories
                _db.Categories.Update(category);
                _db.SaveChanges();
                TempData["success"] = "Sửa Thành Công";
                return RedirectToAction("Index");
            }
            return View();
        }
        //Hiển thị form xác nhận xóa chủng loại
        public IActionResult Delete(int id)
        {
            var category = _db.Categories.FirstOrDefault(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        // Xử lý xóa chủng loại
        public IActionResult DeleteConfirmed(int id)
        {
            var category = _db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(category);
            _db.SaveChanges();
            TempData["success"] = "Xóa Thành Công";
            return RedirectToAction("Index");
        }
    
    }
}

WebBanHang/WebBanHang/Areas/customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;
using WebBanHang.Helpers;

namespace WebBanHang.Areas.customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CartController( ApplicationDbContext db)
        {
            _db = db;
        }
        // hiển thị giỏ hàng
        public IActionResult Index()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart == null)
            {
                cart = new Cart();
            }
            return View(cart);
        }
        public IActionResult AddToCart(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart == null)
                {
                    cart = new Cart();
                }
                cart.Add(product, 1);
                HttpContext.Session.SetJson("CART", cart);
                //return Json(new { msg = "success", qty = cart.Quantity });
                TempData["success"] = "Product added to cart";
                return RedirectToAction("Index", "home");
            }
            return Json(new { msg = "error" });

        }
        public IActionResult Update(int productId,int qty)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart != null)
                {
                    cart.Update(productId, qty);// cap nhat lai so luong
                    HttpContext.Session.SetJson("CART", cart);// luu cart vao session
                    return RedirectToAction("Index");
                }
            }
            return Json(new { msg = "error" });
        }
        public IActionResult remove(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart != null)
                {
                    cart.Remove(productId);// xoa san pham khoi gio
                    HttpContext.Session.SetJson("CART", cart);// luu cart vao session
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        #region API
        public IActionResult AddToCartAPI(int productId)
        {
            var product = _db.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                Cart cart = HttpContext.Session.GetJson<Cart>("CART");
                if (cart == null)
                {
                    cart = new Cart();
                }
                cart.Add(product, 1);
                HttpContext.Session.SetJson("CART", cart);
                 return Json(new { msg = "Product added to cart" , qty=cart.Quantity});
            }
            return Json(new { msg = "error" });

        }
        public IActionResult GetQuanTiTyOfCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("CART");
            if (cart != null)
            {
                return Json(new { qty = cart.Quantity });
            }
            return Json(new { qty = 0 });
        }
        #endregion
    }
}

WebBanHang/WebBanHang/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace WebBanHang.Controllers
{
        public class ProductController : Controller
        {
            private readonly ApplicationDbContext _db;
            private readonly IHostingEnvironment _hosting;
            public ProductController(ApplicationDbContext db, IHostingEnvironment hosting)
            {
                _db = db;
                _hosting = hosting;
            }
            //Hiển thị danh sách sản phẩm
            public IActionResult Index(int ?page)
            {
            //var pageIndex = (int)(page != null ? page : 1);
            //var pageSize = 10;
            //var productList = _db.Products.Include(x => x.Category).ToList();
            ////Thống kê số trang
            ////var pageSum =(int) Math.Ceiling((Decimal)productList.Count / pagesize);
            //var pageSum = productList.Count() / pageSize + (productList.Count() % pageSize > 0 ? 1 : 0);
            //// Truyền dữ liệu cho View
            //ViewBag.pageSum = pageSum;
            //ViewBag.pageIndex = pageIndex;
            //return View(productList.Skip((pageIndex-1)*pageSize).Take(pageSize).ToList());
            return View("showAll");
            }
            //Hiển thị form thêm sản phẩm mới
            public IActionResult Add()
            {
                //truyền danh sách thể loại cho View để sinh ra điều khiển DropDownList
                ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
                return View();
            }

            //Xử lý thêm sản phẩm
            [HttpPost]
        public IActionResult Add(Product product, IFormFile ImageUrl)
            {
                if (ModelState.IsValid) //kiem tra hop le
                {
                    if (ImageUrl != null)
                    {
                        //xu ly upload và lưu ảnh đại diện
                        product.ImageUrl = SaveImage(ImageUrl);
                    }
                    //thêm product vào table Product
                    _db.Products.Add(product);
                    _db.SaveChanges();
                    TempData["success"] = "Thêm thành công";
                    return RedirectToAction("Index");
                }
                ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
                return View();
            }
            //Hiển thị form cập nhật sản phẩm
            public IActionResult Update(int id)
            {
                var product = _db.Products.Find(id);
                if (product == null)
                {
                    return NotFound();
                }
                //truyền danh sách thể loại cho View để sinh ra điều khiển DropDownList
                ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
                return View(product);
            }
            //Xử lý cập nhật sản phẩm
            [HttpPost]
            public IActionResult Update(Product product, IFormFile ImageUrl)
            {
                if (ModelState.IsValid) //kiem tra hop le
                {
                    var existingProduct = _db.Products.Find(product.Id);
                    if (ImageUrl != null)
                    {
                        //xu ly upload và lưu ảnh đại diện mới
                        product.ImageUrl = SaveImage(ImageUrl);

                        //xóa ảnh cũ (nếu có)

                        if (!string.IsNullOrEmpty(existingProduct.ImageUrl))
                        {
                            var oldFilePath = Path.Combine(_hosting.WebRootPath,
                            existingProduct.ImageUrl);
                            if (System.IO.File.Exists(oldFilePath))
                            {
                                System.IO.File.Delete(oldFilePath);
                            }
                        }
                    }
                    else

                    {
                        product.ImageUrl = existingProduct.ImageUrl;
                    }
                    //cập nhật product vào table Product
                    existingProduct.Name = product.Name;
                    existingProduct.Description = product.Description;
                    existingProduct.Price = product.Price;
                    existingProduct.CategoryId = product.CategoryId;
                    existingProduct.ImageUrl = product.ImageUrl;
                    _db.SaveChanges();
                    TempData["success"] = "Sửa thành công";
                    return RedirectToAction("Index");
                }
                ViewBag.CategoryList = _db.Categories.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name
                });
                return View();
            }
            private string SaveImage(IFormFile image)
            {
                //đặt lại tên file cần lưu
                var filename = Guid.NewGuid().ToString() + Path.GetExtension(image.FileName);
                //lay duong dan luu tru wwwroot tren server
                var path = Path.Combine(_hosting.WebRootPath, @"images/products");
                var saveFile = Path.Combine(path, filename);
                using (var filestream = new FileStream(saveFile, FileMode.Create))
                {
                    image.CopyTo(filestream);
                }
                return @"images/products/" + filename;
            }
            //Hiển thị form xác nhận xóa sản phẩm
            public IActionResult Delete(int id)
            {
                var product = _db.Products.Find(id);
                if (product == null)
                {
                    return NotFound();
                }
                return View(product);
            }
            //Xử lý xóa sản phẩm
            [HttpPost, ActionName("Delete")]
            public IActionResult DeleteConfirmed(int id)
            {
                var product = _db.Products.Find(id);
                if (product == null)
                {
                    return NotFound();
                }
                // xoá hình cũ của sản phẩm
                if (!String.IsNullOrEmpty(product.ImageUrl))
                {
                    var oldFilePath = Path.Combine(_hosting.WebRootPath, product.ImageUrl);
                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);

                    }
                }
                // xoa san pham khoi CSDL
                _db.Products.Remove(product);
                _db.SaveChanges();
                TempData["success"] = "Xóa thành công";
                //chuyen den action index
                return RedirectToAction("Index");
            }
        #region Call-API
        //---------- call API-------------
        // lấy tất cả sản phẩm
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _db.Products.Include(x => x.Category).ToList();
            return Json(productList);
        }
        #endregion
    }
}

WebBanHang/WebBanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebBanHang</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-success navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">WebBanHang</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div> 
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Nguyễn Quốc Dư <a asp-area="" asp-controller="Home" asp-action="Privacy">C22A.TH1</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBanHang/WebBanHang/Views/Shared/_LayoutFontEnd.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/shop-template/css/styles.css" rel="stylesheet" />
    <link href="/shop-template/css/Themcss.css" rel="stylesheet" />

</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">

                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">All Products</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Management</a>
                    </li>
                </ul>
                <form class="d-flex" asp-action="Index" asp-controller="Cart">
                    <button class="btn btn-outline-dark" type="submit" href="/customer/Cart">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="ShowCart badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <!-- Header-->

    <!-- Section-->
    <div class="container">
        @RenderBody()
    </div>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBanHang/WebBanHang/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
Swal.fire({
title: "@TempData["success"]",
text: "You clicked the button!",
icon: "success"
});
    </script>
}
@if (TempData["error"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
Swal.fire({
title: "@TempData["error"]",
text: "You clicked the button!",
icon: "error"
});
    </script>
}